# Generated by Django 4.2.7 on 2024-01-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contents', verbose_name='Resim')),
                ('category', models.CharField(max_length=50, verbose_name='Kategori')),
            ],
        ),
    ]
