# Generated by Django 4.2.7 on 2024-01-05 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.category', verbose_name='Kategori'),
        ),
    ]
