# Generated by Django 4.2.7 on 2024-01-05 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_contents_title_alter_contents_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='title',
        ),
        migrations.AlterField(
            model_name='contents',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.category'),
        ),
    ]
