# Generated by Django 4.2.7 on 2024-01-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_alter_contents_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='category',
        ),
    ]
