# Generated by Django 4.2.7 on 2024-01-07 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0004_usermy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermy',
            name='packed',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appUser.packed', verbose_name='Pakedi'),
        ),
    ]
