# Generated by Django 4.2.7 on 2024-01-15 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0007_usermy_user_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermy',
            name='packed',
        ),
    ]
