# Generated by Django 4.2.7 on 2024-01-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0009_usermy_packed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermy',
            name='user_active',
            field=models.CharField(max_length=50, verbose_name='Kullanıcı Dogruluma Linki'),
        ),
    ]
