# Generated by Django 4.2.7 on 2024-01-15 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0010_alter_usermy_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermy',
            name='packed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUser.packed', verbose_name='Pakedi'),
        ),
    ]
